apiVersion: v1
kind: Secret
metadata:
  name: mapsync
  namespace: xonotic
type: Opaque
stringData:
  region: aws-region
  aws.key: aws-key
  aws.secret: aws-secret
  s3.bucket: s3-bucket-name
  s3.prefix: s3-prefix # for example maps/
  sqs.queue: https://sqs.aws-region.amazonaws.com/account-id/queue_name
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mapsync
  namespace: xonotic
  labels:
    app: mapsync
    stack: xonotic
spec:
  replicas: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: mapsync
      stack: xonotic
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mapsync
        stack: xonotic
    spec:
      securityContext:
        runAsUser: 999
        fsGroup: 999
      containers:
      - image: theregulars/mapsync:latest
        imagePullPolicy: Always
        env:
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: mapsync
              key: region
        - name: S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: mapsync
              key: s3.bucket
        - name: S3_PREFIX
          valueFrom:
            secretKeyRef:
              name: mapsync
              key: s3.prefix
        - name: SQS_QUEUE_URL
          valueFrom:
            secretKeyRef:
              name: mapsync
              key: sqs.queue
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: mapsync
              key: aws.key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: mapsync
              key: aws.secret
        name: mapsync
        command: ["mapsync", "-path", "/opt/maps/", '-fifo_path', '/opt/fifo']
        workingDir: "/"
        volumeMounts:
        - name: maps-volume
          mountPath: "/opt/maps"
        - name: admin-volume
          mountPath: "/opt/fifo"
        resources:
          requests:
            cpu: 0.1
            memory: "64Mi"
          limits:
            cpu: 0.2
            memory: "128Mi"
      volumes:
      - name: maps-volume
        hostPath:
          path: /opt/xonotic/maps/
      - name: admin-volume
        hostPath:
          path: /run/xonotic/
